language: csharp
sudo: required

services:
  - docker
before_script:
    - chmod +x buildServer
    - ./buildServer build-local
    - ./buildServer build-docker
script:
    - ./buildServer unit-local
